import { TemplateFieldModel } from './template-field.model';

/**
 * Layout típusok a szekciókhoz
 */
export type LayoutType =
  | 'VERTICAL'
  | 'HORIZONTAL'
  | 'GRID'
  | 'SPLIT'
  | 'CHECKBOX_LIST';

/**
 * Built-in szekció típusok
 */
export type BuiltInSectionType =
  | 'SIZE'
  | 'QUANTITY'
  | 'EXPRESS'
  | 'NOTES'
  | 'FILE_UPLOAD';

/**
 * Preset érték (SPLIT layout gyorsválasztókhoz)
 */
export interface PresetValue {
  label: string;
  value: number | string | Record<string, number>;
}

/**
 * TemplateSection Domain Model
 *
 * Felelősség: Szekció konfiguráció és validáció
 *
 * Layout típusok:
 * - VERTICAL: Mezők egymás alatt (alapértelmezett)
 * - HORIZONTAL: Mezők egymás mellett
 * - GRID: Kártya rács (SELECT/RADIO card megjelenítés)
 * - SPLIT: Bal: inputok, Jobb: presetek (méret választó)
 * - CHECKBOX_LIST: Checkbox kártyák leírással (extrák)
 *
 * Built-in típusok:
 * - SIZE: Méret választó (width/height)
 * - QUANTITY: Mennyiség választó
 * - EXPRESS: Expressz/normál választó
 * - NOTES: Megjegyzés mező
 * - FILE_UPLOAD: Fájl feltöltés
 */
export class TemplateSectionModel {
  constructor(
    public readonly id: string,
    public readonly templateId: string,
    public key: string,
    public title: string,
    public description: string | null,
    public layoutType: LayoutType,
    public columnsCount: number | null,
    public collapsible: boolean,
    public defaultOpen: boolean,
    public showNumber: boolean,
    public order: number,
    public builtInType: BuiltInSectionType | null,
    public presets: PresetValue[] | null,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public fields: TemplateFieldModel[] = [],
  ) {}

  /**
   * Factory method: Új szekció létrehozása
   */
  static create(
    templateId: string,
    key: string,
    title: string,
    options: {
      description?: string | null;
      layoutType?: LayoutType;
      columnsCount?: number | null;
      collapsible?: boolean;
      defaultOpen?: boolean;
      showNumber?: boolean;
      order?: number;
      builtInType?: BuiltInSectionType | null;
      presets?: PresetValue[] | null;
    } = {},
  ): TemplateSectionModel {
    // Validate key format
    const keyRegex = /^[a-z_][a-z0-9_]*$/i;
    if (!keyRegex.test(key)) {
      throw new Error(
        'Section key must be alphanumeric with underscores, cannot start with a number',
      );
    }

    if (!title || title.trim().length === 0) {
      throw new Error('Section title cannot be empty');
    }

    const now = new Date();

    return new TemplateSectionModel(
      '', // ID will be generated by DB
      templateId,
      key.toLowerCase(),
      title.trim(),
      options.description?.trim() || null,
      options.layoutType || 'VERTICAL',
      options.columnsCount || null,
      options.collapsible ?? true,
      options.defaultOpen ?? true,
      options.showNumber ?? true,
      options.order ?? 0,
      options.builtInType || null,
      options.presets || null,
      now,
      now,
      [],
    );
  }

  /**
   * Prisma entitásból domain model-lé konvertálás
   */
  static fromPersistence(prismaSection: any): TemplateSectionModel {
    const fields = prismaSection.fields
      ? prismaSection.fields.map((f: any) => TemplateFieldModel.fromPersistence(f))
      : [];

    return new TemplateSectionModel(
      prismaSection.id,
      prismaSection.templateId,
      prismaSection.key,
      prismaSection.title,
      prismaSection.description,
      prismaSection.layoutType as LayoutType,
      prismaSection.columnsCount,
      prismaSection.collapsible,
      prismaSection.defaultOpen,
      prismaSection.showNumber,
      prismaSection.order,
      prismaSection.builtInType as BuiltInSectionType | null,
      prismaSection.presets as PresetValue[] | null,
      prismaSection.createdAt,
      prismaSection.updatedAt,
      fields,
    );
  }

  /**
   * Domain model-ből Prisma entitássá konvertálás
   */
  toPersistence(): any {
    return {
      id: this.id || undefined,
      templateId: this.templateId,
      key: this.key,
      title: this.title,
      description: this.description,
      layoutType: this.layoutType,
      columnsCount: this.columnsCount,
      collapsible: this.collapsible,
      defaultOpen: this.defaultOpen,
      showNumber: this.showNumber,
      order: this.order,
      builtInType: this.builtInType,
      presets: this.presets,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    };
  }

  /**
   * Field hozzáadása a szekcióhoz
   */
  addField(field: TemplateFieldModel): void {
    const duplicate = this.fields.find((f) => f.key === field.key);
    if (duplicate) {
      throw new Error(`Field with key "${field.key}" already exists in section`);
    }
    this.fields.push(field);
  }

  /**
   * Field eltávolítása
   */
  removeField(fieldKey: string): void {
    this.fields = this.fields.filter((f) => f.key !== fieldKey);
  }
}
