import { FieldType } from '@prisma/client';

/**
 * TemplateField Domain Model (Value Object)
 *
 * Felelősség: Template field konfiguráció és validáció
 *
 * Field types:
 * - NUMBER: Szám mező (pl. szélesség, magasság)
 * - TEXT: Szöveg mező
 * - SELECT: Legördülő lista
 * - RADIO: Rádiógomb csoport
 * - CHECKBOX: Jelölőnégyzet
 * - TEXTAREA: Hosszú szöveg
 * - FILE: Fájl feltöltés
 *
 * Használat:
 * - Template-ekben definiált mezők
 * - User input gyűjtése
 * - Formula változók (useInFormula = true)
 */
export class TemplateFieldModel {
  constructor(
    public readonly id: string,
    public readonly templateId: string,
    public key: string,
    public type: FieldType,
    public label: string,
    public required: boolean,
    public placeholder: string | null,
    public helpText: string | null,
    public helpContent: any | null,
    public validation: any | null,
    public options: any | null,
    public conditionalRules: any | null,
    public useInFormula: boolean,
    public order: number,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  /**
   * Factory method: Új field létrehozása
   *
   * @param templateId - Template ID (UUID)
   * @param key - Field kulcs (formula változó név, pl. "width_cm")
   * @param type - Field típus
   * @param label - Megjelenített címke
   * @param required - Kötelező mező-e
   * @param useInFormula - Használható-e a formulában
   * @param order - Sorrend (0-indexed)
   * @returns Új TemplateFieldModel instance
   *
   * Validációk:
   * - Key: alfanumerikus + underscore, nem kezdődhet számmal
   * - Label nem lehet üres
   * - Order >= 0
   */
  static create(
    templateId: string,
    key: string,
    type: FieldType,
    label: string,
    required: boolean = false,
    useInFormula: boolean = true,
    order: number = 0,
  ): TemplateFieldModel {
    // Validate key format (alphanumeric + underscore, cannot start with number)
    const keyRegex = /^[a-z_][a-z0-9_]*$/i;
    if (!keyRegex.test(key)) {
      throw new Error(
        'Field key must be alphanumeric with underscores, cannot start with a number',
      );
    }

    if (!label || label.trim().length === 0) {
      throw new Error('Field label cannot be empty');
    }

    if (order < 0) {
      throw new Error('Field order cannot be negative');
    }

    const now = new Date();

    return new TemplateFieldModel(
      '', // ID will be generated by DB
      templateId,
      key.toLowerCase(),
      type,
      label.trim(),
      required,
      null, // placeholder
      null, // helpText
      null, // helpContent
      null, // validation
      null, // options
      null, // conditionalRules
      useInFormula,
      order,
      now,
      now,
    );
  }

  /**
   * Prisma entitásból domain model-lé konvertálás
   */
  static fromPersistence(prismaField: any): TemplateFieldModel {
    return new TemplateFieldModel(
      prismaField.id,
      prismaField.templateId,
      prismaField.key,
      prismaField.type as FieldType,
      prismaField.label,
      prismaField.required,
      prismaField.placeholder,
      prismaField.helpText,
      prismaField.helpContent,
      prismaField.validation,
      prismaField.options,
      prismaField.conditionalRules,
      prismaField.useInFormula,
      prismaField.order,
      prismaField.createdAt,
      prismaField.updatedAt,
    );
  }

  /**
   * Domain model-ből Prisma entitássá konvertálás
   */
  toPersistence(): any {
    return {
      id: this.id || undefined,
      templateId: this.templateId,
      key: this.key,
      type: this.type,
      label: this.label,
      required: this.required,
      placeholder: this.placeholder,
      helpText: this.helpText,
      helpContent: this.helpContent,
      validation: this.validation,
      options: this.options,
      conditionalRules: this.conditionalRules,
      useInFormula: this.useInFormula,
      order: this.order,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    };
  }

  /**
   * Placeholder beállítása
   */
  setPlaceholder(placeholder: string | null): void {
    this.placeholder = placeholder?.trim() || null;
  }

  /**
   * Help text beállítása
   */
  setHelpText(helpText: string | null): void {
    this.helpText = helpText?.trim() || null;
  }

  /**
   * Validation rules beállítása
   *
   * Példa:
   * {
   *   min: 0,
   *   max: 1000,
   *   pattern: "^[0-9]+$"
   * }
   */
  setValidation(validation: any | null): void {
    this.validation = validation;
  }

  /**
   * Options beállítása (SELECT, RADIO típusoknál)
   *
   * Példa:
   * [
   *   { label: "Small", value: "small" },
   *   { label: "Medium", value: "medium" },
   *   { label: "Large", value: "large" }
   * ]
   */
  setOptions(options: any | null): void {
    this.options = options;
  }

  /**
   * Conditional rules beállítása
   *
   * Példa:
   * {
   *   show: { field: "material", value: "wood" },
   *   require: { field: "type", value: "custom" }
   * }
   */
  setConditionalRules(rules: any | null): void {
    this.conditionalRules = rules;
  }
}
