import { ScopeType } from '@prisma/client';
import { TemplateFieldModel } from './template-field.model';
import { TemplateSectionModel } from './template-section.model';

/**
 * Sávos kedvezmény típus
 */
export interface DiscountTier {
  minQty: number;
  maxQty: number | null;
  discount: number;
}

/**
 * Template Domain Model
 *
 * Felelősség: Template üzleti szabályok és validációk
 *
 * Domain logika:
 * - Template létrehozása validációval
 * - Formula validálása
 * - Field-ek kezelése
 * - Template aktiválás/deaktiválás
 * - Scope management
 * - Min/Max mennyiség kezelés
 * - Sávos kedvezmények
 * - Expressz gyártás opció
 *
 * Prisma entitásra történő konverzió (toPersistence/fromPersistence pattern)
 */
/**
 * Mennyiség preset típus
 */
export type QuantityPreset = number | { label: string; value: number };

export class TemplateModel {
  constructor(
    public readonly id: string,
    public readonly shopId: string,
    public name: string,
    public description: string | null,
    public pricingFormula: string,
    public pricingMeta: any | null,
    public scopeType: ScopeType,
    public scopeValues: string[],
    public isActive: boolean,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public fields: TemplateFieldModel[] = [],
    // Szekciók (új rendszer)
    public sections: TemplateSectionModel[] = [],
    // Új mezők
    public minQuantity: number | null = null,
    public maxQuantity: number | null = null,
    public minQuantityMessage: string | null = null,
    public maxQuantityMessage: string | null = null,
    public discountTiers: DiscountTier[] | null = null,
    public hasExpressOption: boolean = false,
    public expressMultiplier: number | null = null,
    public expressLabel: string | null = null,
    public normalLabel: string | null = null,
    // Megjegyzés mező
    public hasNotesField: boolean = false,
    public notesFieldLabel: string | null = null,
    public notesFieldPlaceholder: string | null = null,
    // Mennyiség presetek
    public quantityPresets: QuantityPreset[] | null = null,
  ) {}

  /**
   * Factory method: Új template létrehozása
   *
   * @param shopId - Shop ID (UUID)
   * @param name - Template neve
   * @param description - Leírás (opcionális)
   * @param pricingFormula - Ár kalkulációs formula
   * @param scopeType - Scope típus (PRODUCT, COLLECTION, VENDOR, TAG, GLOBAL)
   * @param scopeValues - Scope értékek (pl. product ID-k)
   * @param fields - Template field-ek
   * @returns Új TemplateModel instance
   *
   * Validációk:
   * - Name nem lehet üres
   * - Formula nem lehet üres
   * - Scope values megfelelő formátum
   */
  static create(
    shopId: string,
    name: string,
    description: string | null,
    pricingFormula: string,
    scopeType: ScopeType,
    scopeValues: string[],
    fields: TemplateFieldModel[] = [],
    sections: TemplateSectionModel[] = [],
  ): TemplateModel {
    // Validációk
    if (!name || name.trim().length === 0) {
      throw new Error('Template name cannot be empty');
    }

    if (!pricingFormula || pricingFormula.trim().length === 0) {
      throw new Error('Pricing formula cannot be empty');
    }

    if (name.length > 255) {
      throw new Error('Template name is too long (max 255 characters)');
    }

    const now = new Date();

    return new TemplateModel(
      '', // ID will be generated by DB
      shopId,
      name.trim(),
      description?.trim() || null,
      pricingFormula.trim(),
      null, // pricingMeta
      scopeType,
      scopeValues,
      true, // isActive by default
      now,
      now,
      fields,
      sections,
    );
  }

  /**
   * Prisma entitásból domain model-lé konvertálás
   *
   * @param prismaTemplate - Prisma Template entitás
   * @returns TemplateModel instance
   */
  static fromPersistence(prismaTemplate: any): TemplateModel {
    const fields = prismaTemplate.fields
      ? prismaTemplate.fields.map((f: any) => TemplateFieldModel.fromPersistence(f))
      : [];

    const sections = prismaTemplate.sections
      ? prismaTemplate.sections.map((s: any) => TemplateSectionModel.fromPersistence(s))
      : [];

    return new TemplateModel(
      prismaTemplate.id,
      prismaTemplate.shopId,
      prismaTemplate.name,
      prismaTemplate.description,
      prismaTemplate.pricingFormula,
      prismaTemplate.pricingMeta,
      prismaTemplate.scopeType as ScopeType,
      prismaTemplate.scopeValues,
      prismaTemplate.isActive,
      prismaTemplate.createdAt,
      prismaTemplate.updatedAt,
      fields,
      // Szekciók
      sections,
      // Új mezők
      prismaTemplate.minQuantity,
      prismaTemplate.maxQuantity,
      prismaTemplate.minQuantityMessage,
      prismaTemplate.maxQuantityMessage,
      prismaTemplate.discountTiers as DiscountTier[] | null,
      prismaTemplate.hasExpressOption ?? false,
      prismaTemplate.expressMultiplier
        ? Number(prismaTemplate.expressMultiplier)
        : null,
      prismaTemplate.expressLabel,
      prismaTemplate.normalLabel,
      // Megjegyzés mező
      prismaTemplate.hasNotesField ?? false,
      prismaTemplate.notesFieldLabel,
      prismaTemplate.notesFieldPlaceholder,
      // Mennyiség presetek
      prismaTemplate.quantityPresets as QuantityPreset[] | null,
    );
  }

  /**
   * Domain model-ből Prisma entitássá konvertálás
   *
   * @returns Prisma compatible object
   */
  toPersistence(): any {
    return {
      id: this.id || undefined, // undefined = DB generates
      shopId: this.shopId,
      name: this.name,
      description: this.description,
      pricingFormula: this.pricingFormula,
      pricingMeta: this.pricingMeta,
      scopeType: this.scopeType,
      scopeValues: this.scopeValues,
      isActive: this.isActive,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
      // Új mezők
      minQuantity: this.minQuantity,
      maxQuantity: this.maxQuantity,
      minQuantityMessage: this.minQuantityMessage,
      maxQuantityMessage: this.maxQuantityMessage,
      discountTiers: this.discountTiers,
      hasExpressOption: this.hasExpressOption,
      expressMultiplier: this.expressMultiplier,
      expressLabel: this.expressLabel,
      normalLabel: this.normalLabel,
      // Megjegyzés mező
      hasNotesField: this.hasNotesField,
      notesFieldLabel: this.notesFieldLabel,
      notesFieldPlaceholder: this.notesFieldPlaceholder,
      // Mennyiség presetek
      quantityPresets: this.quantityPresets,
    };
  }

  /**
   * Template frissítése
   *
   * @param name - Új név (opcionális)
   * @param description - Új leírás (opcionális)
   * @param pricingFormula - Új formula (opcionális)
   * @param scopeType - Új scope type (opcionális)
   * @param scopeValues - Új scope values (opcionális)
   */
  update(
    name?: string,
    description?: string | null,
    pricingFormula?: string,
    scopeType?: ScopeType,
    scopeValues?: string[],
  ): void {
    if (name !== undefined) {
      if (!name || name.trim().length === 0) {
        throw new Error('Template name cannot be empty');
      }
      if (name.length > 255) {
        throw new Error('Template name is too long (max 255 characters)');
      }
      this.name = name.trim();
    }

    if (description !== undefined) {
      this.description = description?.trim() || null;
    }

    if (pricingFormula !== undefined) {
      if (!pricingFormula || pricingFormula.trim().length === 0) {
        throw new Error('Pricing formula cannot be empty');
      }
      this.pricingFormula = pricingFormula.trim();
    }

    if (scopeType !== undefined) {
      this.scopeType = scopeType;
    }

    if (scopeValues !== undefined) {
      this.scopeValues = scopeValues;
    }
  }

  /**
   * Template aktiválása
   */
  activate(): void {
    this.isActive = true;
  }

  /**
   * Template deaktiválása
   */
  deactivate(): void {
    this.isActive = false;
  }

  /**
   * Field hozzáadása
   *
   * @param field - TemplateFieldModel instance
   */
  addField(field: TemplateFieldModel): void {
    // Check for duplicate field keys
    const duplicate = this.fields.find((f) => f.key === field.key);
    if (duplicate) {
      throw new Error(`Field with key "${field.key}" already exists`);
    }

    this.fields.push(field);
  }

  /**
   * Field eltávolítása
   *
   * @param fieldKey - Field kulcsa
   */
  removeField(fieldKey: string): void {
    this.fields = this.fields.filter((f) => f.key !== fieldKey);
  }

  /**
   * Field frissítése
   *
   * @param fieldKey - Field kulcsa
   * @param updates - Frissítendő mezők
   */
  updateField(fieldKey: string, updates: Partial<TemplateFieldModel>): void {
    const field = this.fields.find((f) => f.key === fieldKey);
    if (!field) {
      throw new Error(`Field with key "${fieldKey}" not found`);
    }

    Object.assign(field, updates);
  }
}
